spring:
  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/booker
    username: root
    password: 123456
server:
  port: 8080
#  error:
#    whitelabel:
#      enabled: false